/*
 * AMD GCN ISA Assembler
 *
 * Parser module
 *
 * This software is Copyright 2013, Daniel Bali <balijanosdaniel at gmail.com>,
 * and it is hereby released to the general public under the following terms:
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted.
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#include "parser.h"

static const char field_delimiter[] = ", \t";
static const char comment_delimiter[] = ";\n";

static char* getField(char **line, const char delimiter[])
{
	char *field;

	while (1)
	{
		field = strsep(line, delimiter);
		
		if (field == NULL)
			break;

		if (strlen(field) > 0)
			break;
	}

	return field;
}

/**
 * Parses a whole ISA file line by line
 */
void parseFile(const char *input, const char *output) 
{
	FILE *in_file, *out_file;
	char line[256];

	uint32_t *microcode;
	int microcode_ptr;
	int line_count;
	int i;

	// Count lines to estimate microcode size
	line_count = 0;
	in_file = fopen(input, "r");

	if (in_file == NULL)
		ERROR("opening file \"%s\"", input);

	while (fgets(line, sizeof(line), in_file))
	{
		line_count++;
	}

	fclose(in_file);

	// Allocate space for microcode
	microcode = (uint32_t *) calloc(line_count * 2, sizeof (uint32_t));
	microcode_ptr = 0;

	// Parse each line
	in_file = fopen(input, "r");

	if (in_file == NULL)
		ERROR("opening file \"%s\"", input);

	while (fgets(line, sizeof(line), in_file))
	{
		isa_op_code *result;

		result = parseLine(line);

		if (result == NULL)
			continue;

		microcode[microcode_ptr++] = result->code;

		if (result->literal_set)
		{
			microcode[microcode_ptr++] = result->literal;
		}
	}

	fclose(in_file);

	// Write results to output
	out_file = fopen(output, "w");

	if (out_file == NULL)
		ERROR("opening file \"%s\"", output);

	for (i = 0; i < microcode_ptr; ++i)
	{
		// Pack as little-endian value
		uint32_t src = microcode[i];
		uint32_t dst = (
			((src & 0xFF) << 24)		|
			((src & 0xFF00) << 8)		|
			((src & 0xFF0000) >> 8)		|
			((src & 0xFF000000) >> 24)	
		);

		if (fwrite(&dst, sizeof(uint32_t), 1, out_file) == 0)
			ERROR("writing file \"%s\"", output);
	}

	fclose(out_file);
}

/**
 * Parses a single line of ISA assembly
 *
 * (Work in progress, it only prints the output to stdout yet)
 */
isa_op_code* parseLine(char *line)
{
	isa_op_code *result;
	char *line_strip;
	char *token;
	int i;

	// Allocate space for result op_code
	result = malloc(sizeof(isa_op_code *));

	// Special case for commented lines
	if (line[0] == comment_delimiter[0])
		return NULL;

	// Strip comments
	line_strip = getField(&line, comment_delimiter);

	// Get instruction token
	token = getField(&line_strip, field_delimiter);

	// Skip empty lines
	if (token == NULL)
		return NULL;
	
	for (i = 0; i < isa_instr_count; ++i)
		if (strcmp(isa_instr_list[i].name, token) == 0)
			break;

	if (i == isa_instr_count)
		ERROR("unrecognized instruction '%s'\n", token);

	//printf("%s \t", isa_instr_list[i].name);

	// Parse encoding
	// TODO: This should be much better automated
	switch (isa_instr_list[i].encoding)
	{
		case SOP2: 
			{
				// Raw strings
				char **args;
				char *sdst_str, *ssrc1_str, *ssrc0_str;	

				// Parse sdst, ssrc1, ssrc0
				parseOperand(&line_strip, &sdst_str);
				parseOperand(&line_strip, &ssrc0_str);
				parseOperand(&line_strip, &ssrc1_str);

				args = (char **) calloc(3, sizeof(char *));
				args[0] = sdst_str;
				args[1] = ssrc0_str;
				args[2] = ssrc1_str;

				*result = parseSOP2Instruction(isa_instr_list[i], args);
			}
			break;
		case VOP2:
			{
				// TODO: some VOP2 instructions (v_add_i32) can take a 
				// parameter (vcc), which is not 100% clear to me yet.
				// According to the docs: v_add_i32 "Produces a carry out 
				// in VCC or a scalar register."
				//
				// However, I don't see how this parameter could affect the
				// generated bytecode. The only way I see is that if the 
				// parameter is different from "vcc" the instruction will
				// be turned into a VOP3b type instruction. This can then
				// load the carry out into a given SGPR.

				// Raw strings
				char **args;
				char *vdst_str, *src0_str, *vsrc1_str;	// *vcc_str

				// Parse vdst, vcc, src0, vsrc1
				parseOperand(&line_strip, &vdst_str);
				//parseOperand(&line_strip, &vcc_str);
				parseOperand(&line_strip, &src0_str);
				parseOperand(&line_strip, &vsrc1_str);
				
				args = (char **) calloc(4, sizeof(char *));
				args[0] = vdst_str;
				//args[1] = vcc_str;
				args[1] = src0_str;
				args[2] = vsrc1_str;

				*result = parseVOP2Instruction(isa_instr_list[i], args);
			} 
			break;
		default:
			WARNING("Unsupported encoding type for instruction '%s'", 
				isa_instr_list[i].name);
			return NULL;
			break;
	}

	return result;
}

/**
 * Pre-parses an operand using strsep
 * Removes any trailing new-line
 */
void parseOperand(char **line, char **res)
{
	while (strlen(*res = strsep(line, field_delimiter)) == 0);

	if ((*res)[strlen(*res)-1] == '\n')
		(*res)[strlen(*res)-1] = '\0';
}